export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const UPDATE_PRICE_PARALLEL = 'UPDATE_PRICE_PARALLEL';
export const UPDATE_PRICE_MEDIUM = 'UPDATE_PRICE_MEDIUM';
export const UPDATE_PRICE_FIRST_LINE = 'UPDATE_PRICE_FIRST_LINE';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const IS_FETCHING = 'IS_FETCHING'
export const RESET_FORM = 'RESET_FORM'